### ISSUE TITLE
Autocomplete adds extra opening tag

### ISSUE THREAD

**Issue by GreyGreyman** [mrmartineau/HTML5#14]
If I open tag manually, start writing it, than autocomplete, it adds an extra opening tag, which is really annoying.

**Comment by shavonn** [comment]
I have this issue as well.

`<<div>`
	
`</div>`

**Comment by spankrrules** [comment]
Please solve this! This is annoying to me too.

**Comment by treedbox** [comment]
It's very easy to solve:
http://treedbox.com/dev/div.sublime-snippet
save this file inside a folder in Packages (Preferences > Browse Packages...)
you can create a new folder or just put it inside the HTML5 folder.

Basically using "&lt;" let you include < in tabTrigger
: )

**Comment by dare023** [comment]
I also have this issue, will try suggestion above, but it would be nice to have it fixed.

**Comment by mrmartineau** [comment]
Hi all, all tabtriggers for this package are based on the tag name itself, not an opening angle bracket and the tag name, so if you type `<div` and then hit tab, you will get undesired results. Instead, just type `div` and you will be fine. 

See the snippet for reference: https://github.com/mrmartineau/HTML5/blob/35de330062d22a0ad1ace3fa72bf003cda70f10a/Elements/Grouping%20content/div.sublime-snippet

Also, I actually have this package disabled because [Emmet](http://emmet.io) is so much better. You guys should check it out.
